services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: print13
      MYSQL_DATABASE: vollmed
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
